version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - NETWORK_IP=0.0.0.0
    ports:
      - "8080:8080"
    volumes:
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    command: [ "python", "-u", "app.py" ]
