version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./dist:/app/dist
      - ./index.html:/app/index.html
      - ./app.py:/app/app.py
      - ./requirements.txt:/app/requirements.txt
    command: [ "python", "-u", "app.py" ]
